#!/usr/bin/env bash

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  60             \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# Setup spaces
function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 web
setup_space 2 emacs
setup_space 3 emacs
setup_space 4 other
setup_space 5 other
setup_space 6 other
setup_space 7 other
setup_space 8 media
setup_space 9 social

# app rules
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^mono64$" manage=off

yabai -m rule --add app="^Firefox$" space=^1

# Emacs
yabai -m rule --add app="^Emacs$" space=^2

# Media
yabai -m rule --add app="^mpv$" space=^8
yabai -m rule --add app="^Overcast$" space=^8
yabai -m rule --add app="^Radio Garden$" space=^8
yabai -m rule --add app="^Podcasts$" space=^8
yabai -m rule --add app="^Spotify$" space=^8

# Social
yabai -m rule --add app="^Telegram$" space=^9
yabai -m rule --add app="^Signal$" space=^9
yabai -m rule --add app="^Microsoft Teams classic$" space=^9 manage=off
yabai -m rule --add app="^Microsoft Teams$" space=^9 manage=off
yabai -m rule --add app="^Discord$" space=^9

echo "yabai configuration loaded.."

